"""Reasoning notes generator — produces a human-readable markdown review document."""
from __future__ import annotations

# MITRE tactic ID → display name
_TACTIC_NAMES: dict[str, str] = {
    "TA0001": "Initial Access",
    "TA0002": "Execution",
    "TA0003": "Persistence",
    "TA0004": "Privilege Escalation",
    "TA0005": "Defense Evasion",
    "TA0006": "Credential Access",
    "TA0007": "Discovery",
    "TA0008": "Lateral Movement",
    "TA0009": "Collection",
    "TA0010": "Exfiltration",
    "TA0011": "Command and Control",
    "TA0040": "Impact",
    "TA0042": "Resource Development",
    "TA0043": "Reconnaissance",
}


def _tactic_label(tid: str) -> str:
    name = _TACTIC_NAMES.get(tid, "")
    return f"`{tid}` {name}" if name else f"`{tid}`"


def generate_reasoning_notes(result: dict, reasoning: dict) -> str:
    """
    Build a markdown document explaining how the analysis results were derived.

    Args:
        result:    ModuleProperty dict (the final JSON output).
        reasoning: Dict with keys build_reasoning, artifact_reasoning, tactic_reasoning.
    """
    lines: list[str] = []

    module_name = result.get("module_name", "")
    analyzed_at = result.get("analyzed_at", "")
    errors      = result.get("errors", [])

    lines += [
        f"# Reasoning Notes: {module_name}",
        "",
        f"> Generated by ProjectAnalysisAgent · {analyzed_at}",
        "",
        "---",
        "",
    ]

    # ── 1. Module Classification ──────────────────────────────────────────────
    lines += [
        "## 1. Module Classification",
        "",
        f"**Category:** `{result.get('module_category', '')}`  ",
    ]
    mf = result.get("module_form", {})
    langs = mf.get("source_language", [])
    lines += [
        f"**Source Language:** {', '.join(langs) if langs else '—'}  ",
        f"**Form Type:** {mf.get('form_type', '—')}  ",
        f"**Has Submodule:** {mf.get('has_submodule', False)}",
        "",
    ]
    tr = reasoning.get("tactic_reasoning", "").strip()
    if tr:
        lines += ["**LLM Reasoning:**", "", tr, ""]
    lines += ["---", ""]

    # ── 2. Functional Features ────────────────────────────────────────────────
    ff = result.get("functional_features", {})
    caps = ff.get("capabilities", [])
    pe   = ff.get("post_exploits", [])
    lines += [
        "## 2. Functional Features",
        "",
        f"**Capabilities:** {', '.join(f'`{c}`' for c in caps) if caps else '—'}  ",
        f"**Post-Exploits:** {', '.join(f'`{p}`' for p in pe) if pe else '—'}",
        "",
    ]
    custom_tags = result.get("custom_tags", [])
    if custom_tags:
        lines += [f"**Custom Tags (vocabulary match):** {', '.join(f'`{t}`' for t in custom_tags)}", ""]
    lines += ["---", ""]

    # ── 3. Build Features ─────────────────────────────────────────────────────
    bf = result.get("build_features", {})
    lines += [
        "## 3. Build Features",
        "",
        f"**Build Tool:** `{bf.get('build_tool', '—')}`  ",
        f"**No Concurrent Build:** {bf.get('no_concurrent_build', False)}  ",
        f"**Build Tool Args:**",
        "",
        f"```",
        bf.get("build_tool_args", ""),
        "```",
        "",
    ]
    params = bf.get("build_params", [])
    if params:
        lines += ["**Build Parameters:**", ""]
        lines += ["| Name | Type | Title | Default | Choices |", "|------|------|-------|---------|---------|"]
        for p in params:
            choices = ", ".join(p.get("choice_list") or []) or "—"
            default = p.get("param_default") or "—"
            lines.append(
                f"| `{p.get('param_name', '')}` "
                f"| {p.get('param_type', '')} "
                f"| {p.get('param_title', '')} "
                f"| {default} "
                f"| {choices} |"
            )
        lines.append("")
    env_os = (bf.get("build_env") or {}).get("build_env_os", "—")
    archive = bf.get("artifacts_archive", "") or "—"
    lines += [
        f"**Build Environment OS:** `{env_os}`  ",
        f"**Artifacts Archive Glob:** `{archive}`",
        "",
    ]
    br = reasoning.get("build_reasoning", "").strip()
    if br:
        lines += ["**LLM Reasoning:**", "", br, ""]
    lines += ["---", ""]

    # ── 4. Execution Components ───────────────────────────────────────────────
    ef = result.get("execution_features", {})
    components = ef.get("components", [])
    lines += ["## 4. Execution Components", ""]
    if components:
        lines += ["| Component | Type | Arch | OS | Multi-Instance | Pathname |",
                  "|-----------|------|------|----|---------------|----------|"]
        for c in components:
            exec_type = ", ".join(c.get("exec_type", []))
            exec_arch = ", ".join(c.get("exec_arch", []))
            exec_os   = ", ".join(c.get("exec_os", []))
            pathname  = c.get("pathname") or "—"
            multi     = "Yes" if c.get("multi_instance") else "No"
            lines.append(
                f"| {c.get('name', '')} | `{exec_type}` | {exec_arch} | {exec_os} | {multi} | `{pathname}` |"
            )
        lines.append("")
    else:
        lines += ["_(no components identified)_", ""]

    ar = reasoning.get("artifact_reasoning", "").strip()
    if ar:
        lines += ["**LLM Reasoning:**", "", ar, ""]

    # payload_info
    pi = result.get("payload_info")
    if pi:
        lines += [
            "**Payload Info:**",
            "",
            f"- Exec Type: {', '.join(pi.get('payload_exec_type', []))}"
            f"  \n- Execution Method: {', '.join(pi.get('execution_method', []))}"
            f"  \n- Delivery: {pi.get('delivery_type', '—')}"
            f"  \n- Target Path: {pi.get('payload_target_path') or '—'}",
        ]
        pt = pi.get("payload_transform_info")
        if pt:
            ki = (pt.get("keyinfo") or {})
            lines.append(
                f"  \n- Transform: algorithm=`{pt.get('algorithm') or '—'}`, "
                f"key size={ki.get('size', '—')}, "
                f"key input={ki.get('key_input_type', '—')}"
            )
        lines.append("")
    lines += ["---", ""]

    # ── 5. MITRE ATT&CK ───────────────────────────────────────────────────────
    tactics    = result.get("mitre_tactics", [])
    techniques = result.get("mitre_techniques", [])
    lines += [
        "## 5. MITRE ATT&CK",
        "",
        "**Tactics:**",
        "",
    ]
    if tactics:
        for t in tactics:
            lines.append(f"- {_tactic_label(t)}")
    else:
        lines.append("_(none)_")
    lines += [
        "",
        f"**Techniques:** {', '.join(f'`{t}`' for t in techniques) if techniques else '_(none)_'}",
        "",
        "> Tactics/techniques include both LLM-identified IDs and deterministic enrichment",
        "> from custom tag lookups (`_TAG_MITRE`) and code signal pattern matching (`_SIGNAL_MITRE`).",
        "",
        "---",
        "",
    ]

    # ── 6. Language Composition ───────────────────────────────────────────────
    # (not in result dict — informational only from what's available)
    lines += [
        "## 6. Analysis Errors",
        "",
    ]
    if errors:
        for err in errors:
            lines.append(f"- ⚠️ {err}")
    else:
        lines.append("_(none)_")
    lines.append("")

    return "\n".join(lines)
